#!/usr/bin/env bash
# Bash script that transfers a file from a client to a server using scp.

if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -i "$4" "$1" "$3@$2":~/
fi

