#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes:
#+ display hours from 0 to 12
# display minutes from 1 to 59

hours=0
minutes=1

echo "Hour: $hours"
while [ $hours -lt 12 ]
do
	if [ $minutes = 59 ]
	then
		hours=$((hours+1))
		echo "$minutes"
		minutes=1
		echo "Hour: $hours"
	else
		echo "$minutes"
		minutes=$((minutes+1))
	fi
done
