#!/usr/bin/env bash
# configures an Ubuntu server with the below requirements
#+ localhost resolves to 127.0.0.2
#+ facebook.com resolves to 8.8.8.8

cp etc/hosts ~/hosts.new
echo "localhost    127.0.0.1" > ~/hosts.new
echo "facebook.com    8.8.8.8" >> ~/hosts.new
cp -f ~/hosts.new etc/hosts
