#!/usr/bin/env bash
# Script to connect to a server using a private key
private_key_path="~/.ssh/school"
user="ubuntu"
server_ip="52.3.253.239"
# Connect using ssh
ssh -i $private_key_path $user@$server_ip
